apiVersion: v1
kind: Service
metadata:
  name: cd-pipeline
  namespace: default
spec:
  selector:
    app: cd-pipeline # Match the label used in the deployment.yaml
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 
