apiVersion: v1
kind: Service
metadata:
  name: cicd-pipeline
  namespace: default
spec:
  selector:
    app: cicd-pipeline-1.0.0-13  # Match the label used in the deployment.yaml
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 
